name: 'ESP-IDF v4.x installer'
description: 'GitHub Action to install Espressif IoT Development Framework v4.x for building ESP32 code.'

branding:
  icon: check
  color: purple

inputs:
  esp_idf_version:
    description: 'Required ESP-IDF version (v4.1, release/v4.2, ...)'
    required: false
    default: 'latest'

runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/install.sh ${{ inputs.esp_idf_version }}
      shell: bash
